# -*- coding: utf-8 -*-
"""heartdiseasepredictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G7ep-rgbbmSFxEBW0UIDegKLQ9fUolsx
"""

from google.colab import files
uploaded = files.upload()

!pip install ydata_profiling

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("heart_disease_uci.csv")

from ydata_profiling import ProfileReport
prof = ProfileReport(df)
prof.to_file(output_file='output.html')

df1 = df.drop(columns = ['id', 'dataset', 'ca', 'thal'])

df1['chol'] = df1['chol'].replace(0, np.nan)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df1.drop(columns = ['num']), df['num'], test_size = 0.2, random_state = 42)

q1 = X_train['trestbps'].quantile(0.25)
q3 = X_train['trestbps'].quantile(0.75)
iqr = q3- q1
min = q1 - 1.5 * iqr
max = q3 + 1.5  * iqr

X_train['trestbps'] = np.where(X_train['trestbps'] > max, max, np.where(X_train['trestbps'] < min, min, X_train['trestbps']))

X_train.sample(5)

from sklearn.impute import KNNImputer, SimpleImputer

from sklearn.compose import ColumnTransformer

from sklearn.preprocessing import StandardScaler, OneHotEncoder, PowerTransformer, OrdinalEncoder

from sklearn.pipeline import Pipeline

#['chol' , 'oldpeak', 'thalch']
group1 = Pipeline([
    ('num', KNNImputer(n_neighbors = 5, weights = 'distance')),
    ('scale',StandardScaler())
])

#['cp', 'restecg']
group2 = Pipeline([
    ('cat', SimpleImputer(strategy = 'most_frequent')),
    ('encode', OneHotEncoder(drop = 'first', sparse_output= False))
])

#tresbps
group3 = Pipeline([
    ('num', KNNImputer(n_neighbors = 5, weights = 'distance')),
    ('transform', PowerTransformer()),
    ('scale',StandardScaler())
])

#age
group4 = Pipeline([
    ('scale',StandardScaler())
])

#slope
group5 = Pipeline([
    ('impute', SimpleImputer(strategy = 'most_frequent')),
    ('ordinal', OrdinalEncoder(categories = [['downsloping', 'flat', 'upsloping']]))
])

#exang,fbs
group6 = Pipeline([
    ('impute', SimpleImputer(strategy = 'most_frequent'))
])

#sex
group7 = Pipeline([
    ('encode', OneHotEncoder(drop = 'first', sparse_output= False))
])

trf = ColumnTransformer([
    ('group1', group1, ['chol' , 'oldpeak', 'thalch']),
    ('group2', group2, ['cp', 'restecg']),
    ('group3', group3, ['trestbps']),
    ('group4', group4, ['age']),
    ('group5', group5, ['slope']),
    ('group6', group6, ['exang', 'fbs']),
    ('group7', group7, ['sex'])
])

from sklearn.decomposition import PCA

pca = PCA(n_components = None)

from sklearn.linear_model import LogisticRegression

lg = LogisticRegression(multi_class='multinomial')

pipe = Pipeline([
  ('trf', trf),
  ('pca', pca),
  ('lg', lg)
])

pipe.fit(X_train, y_train)

y_pred = lg.predict(X_test)

